apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: {{ include "actions-runner.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    spec:
      {{- if not .Values.isOrganizationRunner }}
      repository: {{ .Values.repository }}
      {{- end }}
      {{- if .Values.isOrganizationRunner }}
      organization: {{ .Values.organization }}
      {{- end }}
      labels:
        {{- toYaml .Values.labels | nindent 8 }}
      dockerEnabled: {{ .Values.dockerEnabled }}
      dockerdWithinRunnerContainer: {{ .Values.dockerdWithinRunnerContainer }}
      image: {{ .Values.image }}
      env:
        {{- toYaml .Values.env | nindent 8 }}
