postgres:
  name: postgres
  statefulSet:
    image: postgres:14.1
    replicaCount: 1
  service:
    port: 5432
  resources: { }

app:
  name: app
  deployment:
    replicaCount: 1
  api:
    deployment:
      image:
        repository: ghcr.io/senfu-labs/senfu
        tag: api-1.2.0
      resources:
        limits:
          cpu: "0.5"
        requests:
          cpu: "0.2"
    service:
      ports:
        name: site-port
        type: ClusterIP
        port: 80
  site:
    deployment:
      image:
        repository: ghcr.io/senfu-labs/senfu
        tag: site-1.6.0
      resources:
        limits:
          cpu: "0.5"
        requests:
          cpu: "0.2"
    service:
      ports:
        site:
          name: site-port
          port: 80
        sftp:
          name: sftp-port
          port: 2300

secrets:
  dbPass: pg-secret
  cookieSecret: app-secrets

volumes:
  pvc:
    name: pano-pv-claim
    storage: 20Gi
  configMapName: site-nginx-config
