postgres:
  name: postgres
  secret:
    name: pg-secret
    user: postgres
    password: mysecretpassword
    superUserPassword: superSecretAdminPassword
    replicationUserPassword: replicationUserPassword
    adminUserPassword: adminUserPassword
    appUserPassword: appUserPassword
    db: mydatabase
  cm:
    base:
      name: base-kubegres-config
    custom:
      name: postgres-conf
  statefulSet:
    image: postgres:14.1
    replicaCount: 1
  service:
    port: 5432
  resources: { }

app:
  name: app
  deployment:
    replicaCount: 1
  api:
    deployment:
      image:
        repository: senfu
        tag: api-1.2.0
      resources:
        limits:
          cpu: "0.5"
        requests:
          cpu: "0.2"
    service:
      ports:
        name: site-port
        type: ClusterIP
        port: 80
  site:
    deployment:
      image:
        repository: senfu
        tag: site-1.6.0
      resources:
        limits:
          cpu: "0.5"
        requests:
          cpu: "0.2"
    service:
      ports:
        site:
          name: site-port
          port: 80
        sftp:
          name: sftp-port
          port: 2300
  secret:
    name: app-secrets
    cookieSecret: cookieSecret

volumes:
  pv:
    storage: 10Gi
    storageClass: do-block-storage
  pvc:
    name: postgres-db-postgres-0
    storage: 10Gi
    storageClass: do-block-storage
  configMapName: site-nginx-config
