{{- if .Values.dns.cloudflare }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "letsencrypt-issuers.cloudflare" . }}
type: Opaque
data:
  token: {{ .Values.dns.cloudflare.token | b64enc }}
{{- end }}
