{{- if .Values.externalSecrets.enabled -}}
{{- $fullName := printf "senfu-%s" (include "senfu.fullname" .) -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.secretStoreName }} # name of the SecretStore (or kind specified)
  target:
    name: {{ $fullName }}
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecrets.secrets }}
    - secretKey: {{ .key }}
      remoteRef:
        key: {{ .name }}
    {{- end }}
{{- end }}
