apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secret.name }}
  namespace: default
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.secret.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.secret.password | b64enc | quote }}
  POSTGRES_DB: {{ .Values.postgres.secret.db | b64enc | quote }}
  superUserPassword: {{ .Values.postgres.secret.superUserPassword | b64enc | quote }}
  replicationUserPassword: {{ .Values.postgres.secret.replicationUserPassword | b64enc | quote }}
  adminUserPassword: {{ .Values.postgres.secret.adminUserPassword | b64enc | quote }}
  appUserPassword: {{ .Values.postgres.secret.appUserPassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.secret.name }}
  namespace: default
type: Opaque
data:
  cookieSecret: {{ .Values.app.secret.cookieSecret | b64enc | quote }}
