apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secretName }}
  namespace: default
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}
  POSTGRES_DB: {{ .Values.postgres.db | b64enc | quote }}
  superUserPassword: {{ .Values.postgres.superUserPassword | b64enc | quote }}
  replicationUserPassword: {{ .Values.postgres.replicationUserPassword | b64enc | quote }}
  adminUserPassword: {{ .Values.postgres.adminUserPassword | b64enc | quote }}
  appUserPassword: {{ .Values.postgres.appUserPassword | b64enc | quote }}
