apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - name: service-port
      port: {{ .Values.app.site.service.ports.site.port }}
      targetPort: {{ .Values.app.site.service.ports.site.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}
  labels:
    app: {{ .Values.postgres.name }}
spec:
  selector:
    app: {{ .Values.postgres.name }}
  ports:
    - name: postgres-port
      port: {{ .Values.postgres.service.port }}
