# By default you will need to enter organization name to make runners available to all repositories
# Set isOrganizationRunner flag to false to specify a single repository instead.
isOrganizationRunner: true
repository: ""
organization: ""

nameOverride: ""
fullnameOverride: ""

labels:
  - dind

# Number of runners to be deployed
replicaCount: 2

image: summerwind/actions-runner-dind:latest

# resources:
#   limits:
#     cpu: "250m"
#     memory: "250Mi"
#   requests:
#     cpu: "125m"
#     memory: "125Mi"

# true (default) = A privileged docker sidecar container is included in the runner pod.
# false = A docker sidecar container is not included in the runner pod and you can't use docker.
# If set to false, there are no privileged container and you cannot use docker.
dockerEnabled: false

# false (default) = Docker support is provided by a sidecar container deployed in the runner pod.
# true = No docker sidecar container is deployed in the runner pod but docker can be used within teh runner container instead. The image summerwind/actions-runner-dind is used by default.
dockerdWithinRunnerContainer: true

workDir: /home/runner/work

env: []
