# By default you will need to enter organization name to make runners available to all repositories
# Set isOrganizationRunner flag to false to specify a single repository instead.
isOrganizationRunner: false
repository: ""
organization: ""

nameOverride: ""
fullnameOverride: ""

# Number of runners to be deployed
replicaCount: 2

image: summerwind/actions-runner-dind

resources:
  limits:
    cpu: "1000m"
    memory: "1Gi"
  requests:
    cpu: "125m"
    memory: "125Mi"

# false (default) = Docker support is provided by a sidecar container deployed in the runner pod.
# true = No docker sidecar container is deployed in the runner pod but docker can be used within teh runner container instead. The image summerwind/actions-runner-dind is used by default.
dockerdWithinRunnerContainer: true

env: []
