# By default you will need to enter organization name to make runners available to all repositories
# Set isOrganizationRunner flag to false to specify a single repository instead.
isOrganizationRunner: true
repository: ""
organization: ""

labels:
  - ephemeral
  - dind
  - infraway

nameOverride: ""
fullnameOverride: ""

image: infraway/github-actions-runner:dind

# false (default) = Docker support is provided by a sidecar container deployed in the runner pod.
# true = No docker sidecar container is deployed in the runner pod but docker can be used within teh runner container instead. The image summerwind/actions-runner-dind is used by default.
dockerdWithinRunnerContainer: true

env:
  - name: RUNNER_FEATURE_FLAG_EPHEMERAL
    value: "true"

# Number of runners to be deployed, can be 0 if using autoscaling
replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  scaleDownDelaySecondsAfterScaleOut: 300
  duration: "10m"
