{{- range $index, $registry := .Values.registries }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apps-serviceaccount.fullname" $ }}-{{ $index }}
  labels:
  {{- include "apps-serviceaccount.labels" $ | nindent 4 }}
  {{- with $.Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ print (include "docker-config" $registry | fromYaml | toJson | b64enc) }}
---
{{- end }}
