{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "apps-serviceaccount.serviceAccountName" . }}
  labels:
    {{- include "apps-serviceaccount.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
imagePullSecrets:
  {{- range $index, $registry := .Values.registries }}
  - name: {{ include "apps-serviceaccount.fullname" $ }}-{{ $index }}
  {{- end }}
  {{- range $secret := .Values.extra_secrets }}
  - name: {{ $secret | quote }}
  {{- end }}
{{- end }}
